return {
  { "moonkose/neocodeium", enabled = false },
  { "MagicDuck/grug-far.nvim" },
  { "rose-pine/neovim", enabled = false },
  { "frenzyexists/aquarium-vim", enabled = false },
  { "rebelot/kanagawa.nvim", enabled = false },
  { "nyoom-engineering/oxocarbon.nvim", enabled = false },
  { "eldritch-vim/eldritch-theme", enabled = false },
  { "slugbyte/lackluster", enabled = false },
  { "0xstepit/flow.nvim", enabled = true },
  { "bluz71/vim-moonfly-colors", enabled = false },
  { "zootedb0t/citruszest.nvim", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "supermaven-inc/supermaven-nvim", enabled = true },
  { "sainnhe/gruvbox-material", enabled = false },
  { "EdenEast/nightfox.nvim", enabled = false },
  { "rose-pine/neovim", enabled = false },
  { "craftzdog/solarized-osaka.nvim", enabled = false },
  { "ThePrimeagen/vim-be-good", enabled = false },
}
